### ISSUE TITLE
ヘッダーの「バックエンド」「フロントエンド」文字サイズについて@ともひで

### ISSUE THREAD

**Issue by ryu1s** [clenzy-dev/clenzy-map-theme#13]
ロゴの修正の件ありがとうございました。いい感じです。
一点ご相談で、ロゴの「CLENZY MAP」の文字と、右側の「バックエンドエンジニア」「フロントエンドエンジニア」の文字のバランスが違和感あるかなと思ったのですが、ご検討のほどよろしくお願いいたします。

**Comment by hidetomo0102** [comment]
https://github.com/clenzy-dev/clenzy-map-theme/commit/d66737b101ff0055b8abe431154ba38efa0b5022

こちらのコミットで修正しましたので、ステージング確認ください！

**Comment by ryu1s** [comment]
さすが仕事お早い。ありがとうございます！lgtm
