### ISSUE TITLE
スマホ版ヘッダー幅修正@ともひで

### ISSUE THREAD

**Issue by ryu1s** [clenzy-dev/clenzy-map-theme#14]
PC版と同様のロゴ使用した方が、ヘッダーの幅すっきりして良いかなと思いました！いかがでしょうか。

**Comment by hidetomo0102** [comment]
https://github.com/clenzy-dev/clenzy-map-theme/commit/f7793a1c9f352ef8fafc69460487ab4f7d6c3986

ロゴの縦幅を70pxに調整

**Comment by ryu1s** [comment]
lgtm
