### ISSUE TITLE
デバイス間のフォント違い修正。

### ISSUE THREAD

**Issue by ryu1s** [clenzy-dev/clenzy-map-theme#15]
見る端末によってフォントが変わってしまう部分がある。（発見しているのはサイドバーの【前の記事・次の記事】部分）
前の記事、次の記事の部分は、よく読まれている記事のフォントに統一。
後ほど写真追加します

**Comment by kento-777** [comment]
Clome Edgeともに問題ないです。

**Comment by ryu1s** [comment]
lgtm!!!
